#!/usr/bin/env python3
"""Embed the standalone HIP input kernel as self-contained hiprtc source."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'hip/mvp1/candidate_input_256.hip'
TARGET = ROOT / 'hip/mvp1/candidate_input_256_source.inc'


def main():
    source = SOURCE.read_text(encoding='utf-8')
    source = re.sub(r'^#include .*\n', '', source, flags=re.MULTILINE)
    source = re.sub(r'\buint16_t\b', 'unsigned short', source)
    source = re.sub(r'\bsize_t\b', 'unsigned long long', source)
    if 'extern "C" __global__ void k_candidate_input_256' not in source:
        raise ValueError('expected candidate input kernel not found')
    if ')HIPINPUT"' in source:
        raise ValueError('source contains raw-string delimiter')
    embedded = ('// Generated by tools/embed_candidate_input_256.py; do not edit.\n'
                'static const char kCandidateInput256Source[] = R"HIPINPUT(\n'
                + source + ')HIPINPUT";\n')
    TARGET.write_text(embedded, encoding='utf-8')
    print(TARGET.relative_to(ROOT))


if __name__ == '__main__':
    main()
